name: enterprise-app

on:
  workflow_dispatch:
  push:
    paths:
      - apps/enterprise/**
      - apps/shared/**
      - .github/workflows/enterprise-app.yml
  pull_request:
    branches:
      - main
      - develop
    paths:
      - apps/enterprise/**
      - apps/shared/**
      - .github/workflows/enterprise-app.yml

env:
  REACT_APP_SENTRY_KEY: "https://0bb9b523ea9c4d36b42af5d11f52dade@o4505212736372736.ingest.sentry.io/4505228892241920"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get yarn cache dir
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install
        working-directory: ./apps/enterprise

      - name: Build source code.
        run: yarn run build
        working-directory: ./apps/enterprise

      - name: Publish to Cloudflare Pages
        if: github.event_name == 'push'
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: 620ff29bbd515d2848f5306578bd1d1d
          projectName: enterprise-protocol-app
          directory: apps/enterprise/build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
